# Generated by Django 2.2.5 on 2020-09-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=140)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.TextField(max_length=80)),
                ('price', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('address', models.TextField(max_length=140)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('beds', models.IntegerField()),
                ('badrooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
