# Generated by Django 2.2.5 on 2020-09-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_instant_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
