# Generated by Django 2.2.5 on 2020-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200901_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ManyToManyField(to='rooms.RoomType'),
        ),
    ]
